### ISSUE TITLE
[Line 220] src/sem/graphreader/RaspGraphReader.java

### ISSUE THREAD

**Issue by khatribharat** [marekrei/semgraph#1]
Can you explain why the 'if' condition in line 220 contains a check for 'graph != null' ? Since I suppose the condition 'section.startsWith("gr-list: ")' and this condition are redundant.

**Comment by marekrei** [comment]
It's an extra check to make sure the graph has been created in a previous iteration. Redundant for the program, but added for code clarity and maintainability. I wouldn't really say it's an "issue".
